<?php

    require(__DIR__ . DIRECTORY_SEPARATOR . "Builder.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Builder" . DIRECTORY_SEPARATOR . "Declaration.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Builder" . DIRECTORY_SEPARATOR . "Class_.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Builder" . DIRECTORY_SEPARATOR . "ClassConst.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Builder" . DIRECTORY_SEPARATOR . "FunctionLike.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Builder" . DIRECTORY_SEPARATOR . "Function_.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Builder" . DIRECTORY_SEPARATOR . "Interface_.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Builder" . DIRECTORY_SEPARATOR . "Method.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Builder" . DIRECTORY_SEPARATOR . "Namespace_.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Builder" . DIRECTORY_SEPARATOR . "Param.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Builder" . DIRECTORY_SEPARATOR . "Property.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Builder" . DIRECTORY_SEPARATOR . "Trait_.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Builder" . DIRECTORY_SEPARATOR . "TraitUse.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Builder" . DIRECTORY_SEPARATOR . "TraitUseAdaptation.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Builder" . DIRECTORY_SEPARATOR . "Use_.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "BuilderFactory.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "BuilderHelpers.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Comment.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Comment" . DIRECTORY_SEPARATOR . "Doc.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "ConstExprEvaluationException.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "ConstExprEvaluator.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Error.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "ErrorHandler.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "ErrorHandler" . DIRECTORY_SEPARATOR . "Collecting.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "ErrorHandler" . DIRECTORY_SEPARATOR . "Throwing.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Internal" . DIRECTORY_SEPARATOR . "DiffElem.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Internal" . DIRECTORY_SEPARATOR . "Differ.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "NodeAbstract.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Expr.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Internal" . DIRECTORY_SEPARATOR . "PrintableNewAnonClassNode.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Internal" . DIRECTORY_SEPARATOR . "TokenStream.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "JsonDecoder.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Lexer.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Lexer" . DIRECTORY_SEPARATOR . "Emulative.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Lexer" . DIRECTORY_SEPARATOR . "TokenEmulator" . DIRECTORY_SEPARATOR . "TokenEmulator.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Lexer" . DIRECTORY_SEPARATOR . "TokenEmulator" . DIRECTORY_SEPARATOR . "AttributeEmulator.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Lexer" . DIRECTORY_SEPARATOR . "TokenEmulator" . DIRECTORY_SEPARATOR . "CoaleseEqualTokenEmulator.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Lexer" . DIRECTORY_SEPARATOR . "TokenEmulator" . DIRECTORY_SEPARATOR . "KeywordEmulator.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Lexer" . DIRECTORY_SEPARATOR . "TokenEmulator" . DIRECTORY_SEPARATOR . "EnumTokenEmulator.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Lexer" . DIRECTORY_SEPARATOR . "TokenEmulator" . DIRECTORY_SEPARATOR . "FlexibleDocStringEmulator.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Lexer" . DIRECTORY_SEPARATOR . "TokenEmulator" . DIRECTORY_SEPARATOR . "FnTokenEmulator.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Lexer" . DIRECTORY_SEPARATOR . "TokenEmulator" . DIRECTORY_SEPARATOR . "MatchTokenEmulator.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Lexer" . DIRECTORY_SEPARATOR . "TokenEmulator" . DIRECTORY_SEPARATOR . "NullsafeTokenEmulator.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Lexer" . DIRECTORY_SEPARATOR . "TokenEmulator" . DIRECTORY_SEPARATOR . "NumericLiteralSeparatorEmulator.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Lexer" . DIRECTORY_SEPARATOR . "TokenEmulator" . DIRECTORY_SEPARATOR . "ReadonlyTokenEmulator.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Lexer" . DIRECTORY_SEPARATOR . "TokenEmulator" . DIRECTORY_SEPARATOR . "ReverseEmulator.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "NameContext.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Arg.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Attribute.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "AttributeGroup.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Const_.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Expr" . DIRECTORY_SEPARATOR . "Array_.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Expr" . DIRECTORY_SEPARATOR . "ArrayDimFetch.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Expr" . DIRECTORY_SEPARATOR . "ArrayItem.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "FunctionLike.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Expr" . DIRECTORY_SEPARATOR . "ArrowFunction.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Expr" . DIRECTORY_SEPARATOR . "Assign.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Expr" . DIRECTORY_SEPARATOR . "AssignOp.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Expr" . DIRECTORY_SEPARATOR . "AssignOp" . DIRECTORY_SEPARATOR . "BitwiseAnd.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Expr" . DIRECTORY_SEPARATOR . "AssignOp" . DIRECTORY_SEPARATOR . "BitwiseOr.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Expr" . DIRECTORY_SEPARATOR . "AssignOp" . DIRECTORY_SEPARATOR . "BitwiseXor.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Expr" . DIRECTORY_SEPARATOR . "AssignOp" . DIRECTORY_SEPARATOR . "Coalesce.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Expr" . DIRECTORY_SEPARATOR . "AssignOp" . DIRECTORY_SEPARATOR . "Concat.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Expr" . DIRECTORY_SEPARATOR . "AssignOp" . DIRECTORY_SEPARATOR . "Div.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Expr" . DIRECTORY_SEPARATOR . "AssignOp" . DIRECTORY_SEPARATOR . "Minus.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Expr" . DIRECTORY_SEPARATOR . "AssignOp" . DIRECTORY_SEPARATOR . "Mod.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Expr" . DIRECTORY_SEPARATOR . "AssignOp" . DIRECTORY_SEPARATOR . "Mul.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Expr" . DIRECTORY_SEPARATOR . "AssignOp" . DIRECTORY_SEPARATOR . "Plus.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Expr" . DIRECTORY_SEPARATOR . "AssignOp" . DIRECTORY_SEPARATOR . "Pow.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Expr" . DIRECTORY_SEPARATOR . "AssignOp" . DIRECTORY_SEPARATOR . "ShiftLeft.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Expr" . DIRECTORY_SEPARATOR . "AssignOp" . DIRECTORY_SEPARATOR . "ShiftRight.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Expr" . DIRECTORY_SEPARATOR . "AssignRef.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Expr" . DIRECTORY_SEPARATOR . "BinaryOp.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Expr" . DIRECTORY_SEPARATOR . "BinaryOp" . DIRECTORY_SEPARATOR . "BitwiseAnd.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Expr" . DIRECTORY_SEPARATOR . "BinaryOp" . DIRECTORY_SEPARATOR . "BitwiseOr.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Expr" . DIRECTORY_SEPARATOR . "BinaryOp" . DIRECTORY_SEPARATOR . "BitwiseXor.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Expr" . DIRECTORY_SEPARATOR . "BinaryOp" . DIRECTORY_SEPARATOR . "BooleanAnd.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Expr" . DIRECTORY_SEPARATOR . "BinaryOp" . DIRECTORY_SEPARATOR . "BooleanOr.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Expr" . DIRECTORY_SEPARATOR . "BinaryOp" . DIRECTORY_SEPARATOR . "Coalesce.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Expr" . DIRECTORY_SEPARATOR . "BinaryOp" . DIRECTORY_SEPARATOR . "Concat.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Expr" . DIRECTORY_SEPARATOR . "BinaryOp" . DIRECTORY_SEPARATOR . "Div.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Expr" . DIRECTORY_SEPARATOR . "BinaryOp" . DIRECTORY_SEPARATOR . "Equal.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Expr" . DIRECTORY_SEPARATOR . "BinaryOp" . DIRECTORY_SEPARATOR . "Greater.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Expr" . DIRECTORY_SEPARATOR . "BinaryOp" . DIRECTORY_SEPARATOR . "GreaterOrEqual.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Expr" . DIRECTORY_SEPARATOR . "BinaryOp" . DIRECTORY_SEPARATOR . "Identical.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Expr" . DIRECTORY_SEPARATOR . "BinaryOp" . DIRECTORY_SEPARATOR . "LogicalAnd.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Expr" . DIRECTORY_SEPARATOR . "BinaryOp" . DIRECTORY_SEPARATOR . "LogicalOr.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Expr" . DIRECTORY_SEPARATOR . "BinaryOp" . DIRECTORY_SEPARATOR . "LogicalXor.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Expr" . DIRECTORY_SEPARATOR . "BinaryOp" . DIRECTORY_SEPARATOR . "Minus.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Expr" . DIRECTORY_SEPARATOR . "BinaryOp" . DIRECTORY_SEPARATOR . "Mod.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Expr" . DIRECTORY_SEPARATOR . "BinaryOp" . DIRECTORY_SEPARATOR . "Mul.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Expr" . DIRECTORY_SEPARATOR . "BinaryOp" . DIRECTORY_SEPARATOR . "NotEqual.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Expr" . DIRECTORY_SEPARATOR . "BinaryOp" . DIRECTORY_SEPARATOR . "NotIdentical.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Expr" . DIRECTORY_SEPARATOR . "BinaryOp" . DIRECTORY_SEPARATOR . "Plus.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Expr" . DIRECTORY_SEPARATOR . "BinaryOp" . DIRECTORY_SEPARATOR . "Pow.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Expr" . DIRECTORY_SEPARATOR . "BinaryOp" . DIRECTORY_SEPARATOR . "ShiftLeft.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Expr" . DIRECTORY_SEPARATOR . "BinaryOp" . DIRECTORY_SEPARATOR . "ShiftRight.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Expr" . DIRECTORY_SEPARATOR . "BinaryOp" . DIRECTORY_SEPARATOR . "Smaller.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Expr" . DIRECTORY_SEPARATOR . "BinaryOp" . DIRECTORY_SEPARATOR . "SmallerOrEqual.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Expr" . DIRECTORY_SEPARATOR . "BinaryOp" . DIRECTORY_SEPARATOR . "Spaceship.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Expr" . DIRECTORY_SEPARATOR . "BitwiseNot.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Expr" . DIRECTORY_SEPARATOR . "BooleanNot.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Expr" . DIRECTORY_SEPARATOR . "Cast.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Expr" . DIRECTORY_SEPARATOR . "Cast" . DIRECTORY_SEPARATOR . "Array_.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Expr" . DIRECTORY_SEPARATOR . "Cast" . DIRECTORY_SEPARATOR . "Bool_.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Expr" . DIRECTORY_SEPARATOR . "Cast" . DIRECTORY_SEPARATOR . "Double.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Expr" . DIRECTORY_SEPARATOR . "Cast" . DIRECTORY_SEPARATOR . "Int_.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Expr" . DIRECTORY_SEPARATOR . "Cast" . DIRECTORY_SEPARATOR . "Object_.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Expr" . DIRECTORY_SEPARATOR . "Cast" . DIRECTORY_SEPARATOR . "String_.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Expr" . DIRECTORY_SEPARATOR . "Cast" . DIRECTORY_SEPARATOR . "Unset_.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Expr" . DIRECTORY_SEPARATOR . "ClassConstFetch.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Expr" . DIRECTORY_SEPARATOR . "Clone_.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Expr" . DIRECTORY_SEPARATOR . "Closure.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Expr" . DIRECTORY_SEPARATOR . "ClosureUse.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Expr" . DIRECTORY_SEPARATOR . "ConstFetch.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Expr" . DIRECTORY_SEPARATOR . "Empty_.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Expr" . DIRECTORY_SEPARATOR . "Error.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Expr" . DIRECTORY_SEPARATOR . "ErrorSuppress.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Expr" . DIRECTORY_SEPARATOR . "Eval_.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Expr" . DIRECTORY_SEPARATOR . "Exit_.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Expr" . DIRECTORY_SEPARATOR . "FuncCall.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Expr" . DIRECTORY_SEPARATOR . "Include_.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Expr" . DIRECTORY_SEPARATOR . "Instanceof_.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Expr" . DIRECTORY_SEPARATOR . "Isset_.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Expr" . DIRECTORY_SEPARATOR . "List_.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Expr" . DIRECTORY_SEPARATOR . "Match_.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Expr" . DIRECTORY_SEPARATOR . "MethodCall.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Expr" . DIRECTORY_SEPARATOR . "New_.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Expr" . DIRECTORY_SEPARATOR . "NullsafeMethodCall.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Expr" . DIRECTORY_SEPARATOR . "NullsafePropertyFetch.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Expr" . DIRECTORY_SEPARATOR . "PostDec.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Expr" . DIRECTORY_SEPARATOR . "PostInc.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Expr" . DIRECTORY_SEPARATOR . "PreDec.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Expr" . DIRECTORY_SEPARATOR . "PreInc.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Expr" . DIRECTORY_SEPARATOR . "Print_.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Expr" . DIRECTORY_SEPARATOR . "PropertyFetch.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Expr" . DIRECTORY_SEPARATOR . "ShellExec.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Expr" . DIRECTORY_SEPARATOR . "StaticCall.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Expr" . DIRECTORY_SEPARATOR . "StaticPropertyFetch.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Expr" . DIRECTORY_SEPARATOR . "Ternary.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Expr" . DIRECTORY_SEPARATOR . "Throw_.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Expr" . DIRECTORY_SEPARATOR . "UnaryMinus.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Expr" . DIRECTORY_SEPARATOR . "UnaryPlus.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Expr" . DIRECTORY_SEPARATOR . "Variable.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Expr" . DIRECTORY_SEPARATOR . "Yield_.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Expr" . DIRECTORY_SEPARATOR . "YieldFrom.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Identifier.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "MatchArm.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Name.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Name" . DIRECTORY_SEPARATOR . "FullyQualified.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Name" . DIRECTORY_SEPARATOR . "Relative.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "NullableType.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Param.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Scalar.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Scalar" . DIRECTORY_SEPARATOR . "DNumber.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Scalar" . DIRECTORY_SEPARATOR . "Encapsed.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Scalar" . DIRECTORY_SEPARATOR . "EncapsedStringPart.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Scalar" . DIRECTORY_SEPARATOR . "LNumber.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Scalar" . DIRECTORY_SEPARATOR . "MagicConst.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Scalar" . DIRECTORY_SEPARATOR . "MagicConst" . DIRECTORY_SEPARATOR . "Class_.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Scalar" . DIRECTORY_SEPARATOR . "MagicConst" . DIRECTORY_SEPARATOR . "Dir.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Scalar" . DIRECTORY_SEPARATOR . "MagicConst" . DIRECTORY_SEPARATOR . "File.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Scalar" . DIRECTORY_SEPARATOR . "MagicConst" . DIRECTORY_SEPARATOR . "Function_.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Scalar" . DIRECTORY_SEPARATOR . "MagicConst" . DIRECTORY_SEPARATOR . "Line.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Scalar" . DIRECTORY_SEPARATOR . "MagicConst" . DIRECTORY_SEPARATOR . "Method.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Scalar" . DIRECTORY_SEPARATOR . "MagicConst" . DIRECTORY_SEPARATOR . "Namespace_.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Scalar" . DIRECTORY_SEPARATOR . "MagicConst" . DIRECTORY_SEPARATOR . "Trait_.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Scalar" . DIRECTORY_SEPARATOR . "String_.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Stmt.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Stmt" . DIRECTORY_SEPARATOR . "Break_.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Stmt" . DIRECTORY_SEPARATOR . "Case_.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Stmt" . DIRECTORY_SEPARATOR . "Catch_.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Stmt" . DIRECTORY_SEPARATOR . "ClassLike.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Stmt" . DIRECTORY_SEPARATOR . "Class_.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Stmt" . DIRECTORY_SEPARATOR . "ClassConst.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Stmt" . DIRECTORY_SEPARATOR . "ClassMethod.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Stmt" . DIRECTORY_SEPARATOR . "Const_.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Stmt" . DIRECTORY_SEPARATOR . "Continue_.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Stmt" . DIRECTORY_SEPARATOR . "Declare_.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Stmt" . DIRECTORY_SEPARATOR . "DeclareDeclare.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Stmt" . DIRECTORY_SEPARATOR . "Do_.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Stmt" . DIRECTORY_SEPARATOR . "Echo_.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Stmt" . DIRECTORY_SEPARATOR . "Else_.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Stmt" . DIRECTORY_SEPARATOR . "ElseIf_.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Stmt" . DIRECTORY_SEPARATOR . "Enum_.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Stmt" . DIRECTORY_SEPARATOR . "EnumCase.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Stmt" . DIRECTORY_SEPARATOR . "Expression.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Stmt" . DIRECTORY_SEPARATOR . "Finally_.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Stmt" . DIRECTORY_SEPARATOR . "For_.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Stmt" . DIRECTORY_SEPARATOR . "Foreach_.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Stmt" . DIRECTORY_SEPARATOR . "Function_.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Stmt" . DIRECTORY_SEPARATOR . "Global_.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Stmt" . DIRECTORY_SEPARATOR . "Goto_.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Stmt" . DIRECTORY_SEPARATOR . "GroupUse.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Stmt" . DIRECTORY_SEPARATOR . "HaltCompiler.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Stmt" . DIRECTORY_SEPARATOR . "If_.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Stmt" . DIRECTORY_SEPARATOR . "InlineHTML.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Stmt" . DIRECTORY_SEPARATOR . "Interface_.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Stmt" . DIRECTORY_SEPARATOR . "Label.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Stmt" . DIRECTORY_SEPARATOR . "Namespace_.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Stmt" . DIRECTORY_SEPARATOR . "Nop.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Stmt" . DIRECTORY_SEPARATOR . "Property.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Stmt" . DIRECTORY_SEPARATOR . "PropertyProperty.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Stmt" . DIRECTORY_SEPARATOR . "Return_.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Stmt" . DIRECTORY_SEPARATOR . "Static_.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Stmt" . DIRECTORY_SEPARATOR . "StaticVar.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Stmt" . DIRECTORY_SEPARATOR . "Switch_.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Stmt" . DIRECTORY_SEPARATOR . "Throw_.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Stmt" . DIRECTORY_SEPARATOR . "Trait_.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Stmt" . DIRECTORY_SEPARATOR . "TraitUse.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Stmt" . DIRECTORY_SEPARATOR . "TraitUseAdaptation.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Stmt" . DIRECTORY_SEPARATOR . "TraitUseAdaptation" . DIRECTORY_SEPARATOR . "Alias.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Stmt" . DIRECTORY_SEPARATOR . "TraitUseAdaptation" . DIRECTORY_SEPARATOR . "Precedence.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Stmt" . DIRECTORY_SEPARATOR . "TryCatch.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Stmt" . DIRECTORY_SEPARATOR . "Unset_.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Stmt" . DIRECTORY_SEPARATOR . "Use_.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Stmt" . DIRECTORY_SEPARATOR . "UseUse.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "Stmt" . DIRECTORY_SEPARATOR . "While_.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "UnionType.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Node" . DIRECTORY_SEPARATOR . "VarLikeIdentifier.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "NodeDumper.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "NodeFinder.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "NodeTraverserInterface.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "NodeTraverser.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "NodeVisitor.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "NodeVisitorAbstract.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "NodeVisitor" . DIRECTORY_SEPARATOR . "CloningVisitor.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "NodeVisitor" . DIRECTORY_SEPARATOR . "FindingVisitor.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "NodeVisitor" . DIRECTORY_SEPARATOR . "FirstFindingVisitor.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "NodeVisitor" . DIRECTORY_SEPARATOR . "NameResolver.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "NodeVisitor" . DIRECTORY_SEPARATOR . "NodeConnectingVisitor.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "NodeVisitor" . DIRECTORY_SEPARATOR . "ParentConnectingVisitor.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Parser.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Parser" . DIRECTORY_SEPARATOR . "Multiple.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "ParserAbstract.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Parser" . DIRECTORY_SEPARATOR . "Php5.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Parser" . DIRECTORY_SEPARATOR . "Php7.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "Parser" . DIRECTORY_SEPARATOR . "Tokens.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "ParserFactory.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "PrettyPrinterAbstract.php");
    require(__DIR__ . DIRECTORY_SEPARATOR . "PrettyPrinter" . DIRECTORY_SEPARATOR . "Standard.php");
